baseURL = "http://congnguyenuet.me/Profile_Page/"
languageCode = "en-us"
# theme = "aafu"

[params]
    title = "Blog của NDC"
    author = "TaiTuLangQuen"
    description = "Website title"
    copyright = "2020"

    [params.theme]
        # Available themes are 'light', 'dark', and 'pinkish'
        mainTheme = "light"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Nguyễn Duy Công"
		tagline = "Newbie"
		location = "Hà Nội, Việt Nam"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"
		
        [[params.social.list]]
            class = "fab"
            icon = "fa-facebook"
            url = "https://facebook.com/TaiTuLangQuen"
            title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/NguyenDuyCong"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "https://twitter.com/CongNgu12541939"
            title = "Twitter"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "Bản thân"
        icon = "fas fa-user"
        description = "Không có gì :)))"

    # Education section
    [params.education]
        title = "Học vấn"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Cử nhân"
            college = "UET-VNU"
            dates = "2017 - 2021"
        # [[params.education.list]]
        #     degree = "M.S. in Subject"
        #     college = "University of State-City"
        #     dates = "2013 - 2018"
        #     thesis_title = "Effect of humans on other humans: a study of human behavior."
        #     thesis_link = "#"

    # Project section
    [params.project]
        title = "Dự án"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Kĩ năng"
        panelId = "skill-panel"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "Java, C/C++, Python"
            skillrating = 20
        [[params.skill.list]]
            skill = "HTML, CSS, JavaScript"
            skillrating = 20

    # Hobby section
    [params.hobby]
        title = "Sở thích"
        icon = "fas fa-gamepad"
		
        [[params.hobby.list]]		
		    hobby = "Game"
        [[params.hobby.list]]		
		    hobby = "Phim"
        [[params.hobby.list]]		
		    hobby = "Nhạc"